import {useState} from 'react';
import './App.css';
import StudentDashboard from './pages/StudentDashboard';
import FacultyDashboard from './pages/FacultyDashboard';
import AdminDashboard from './pages/AdminDashboard';
import {api} from './api';

function App(){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState('Student');const [show,setShow]=useState(false);const [remember,setRemember]=useState(false);const [error,setError]=useState('');const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('erpUser'))}catch{return null}});
 const login=async e=>{e.preventDefault();setError('');try{let u;if(username==='demo'&&password==='demo123'){u={username:'demo',fullName:role==='Student'?'Presentation Demo Student':role==='Faculty'?'Presentation Demo Faculty':'System Administrator',role:role==='Administrator'?'ADMIN':role.toUpperCase(),email:'demo@college.local',department:'Demo'};}else{u=await api.login(username,password,role)}setUser(u);if(remember)localStorage.setItem('erpUser',JSON.stringify(u));}catch(err){setError(err.message)}};
 const logout=()=>{localStorage.removeItem('erpUser');setUser(null);setUsername('');setPassword('')};
 if(user){if(user.role==='STUDENT')return <StudentDashboard user={user} onLogout={logout}/>;if(user.role==='FACULTY')return <FacultyDashboard user={user} onLogout={logout}/>;return <AdminDashboard user={user} onLogout={logout}/>}
 return <div className="login-page"><div className="bg-circle c1"/><div className="bg-circle c2"/><div className="login-card"><div className="login-accent"/><div className="logo">🎓</div><h1>College ERP</h1><p className="subtitle">Attendance Management System</p><div className="divider"/><form onSubmit={login}><label>👤 Username / Roll No<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter your username or roll number" required/></label><label>🔒 Password<div className="password-row"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" required/><button type="button" onClick={()=>setShow(!show)}>{show?'🙈':'👁️'}</button></div></label><div className="demo-box"><b>Demo Login</b><span>Username: <b>demo</b> | Password: <b>demo123</b></span><button type="button" onClick={()=>{setUsername('demo');setPassword('demo123')}}>Use Demo Login</button></div><label>🎭 Login As<select value={role} onChange={e=>setRole(e.target.value)}><option>Student</option><option>Faculty</option><option>Administrator</option></select></label><div className="login-options"><label className="check"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Remember Me</label><button type="button" className="link-button" onClick={()=>setError('Please contact the administrator to reset your password.')}>Forgot Password?</button></div>{error&&<div className="login-error">{error}</div>}<button className="signin-button">Sign In</button></form><footer>College ERP • v2.0</footer></div></div>}
export default App;
