spring.application.name=college-erp-backend
server.port=${PORT:8080}

spring.datasource.url=${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/college_erp}
spring.datasource.username=${MYSQL_USERNAME:ashutoshdubey}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/college_erp}
spring.data.mongodb.auto-index-creation=true

management.endpoints.web.exposure.include=health,info
spring.jackson.serialization.write-dates-as-timestamps=false
